-- =====================================================
-- 03_catalogo_minimo.sql (DEFINITIVO)
-- Datos mínimos para poder probar HU-002/004/005 en local.
--
-- A propósito NO inserta provincia/canton/distrito: esos ya
-- quedan cargados con los IDs reales por "002 seed_ubicaciones.sql",
-- y son los mismos IDs que usa el frontend (src/data/ubicaciones.json).
-- Insertar aquí una provincia/canton "San José" de más
-- desalinearía esos IDs otra vez.
--
-- IMPORTANTE: tipo_producto e id_motivo usan columnas IDENTITY.
-- Si en algún momento vuelves a correr este script sobre datos ya
-- existentes (sin pasar primero por 00_reset_local.sql), el IDENTITY
-- NO reinicia solo con un DELETE, y los IDs quedarían desalineados con
-- TIPOS_PRODUCTO_MAP / MOTIVOS_MAP del frontend (denunciaService.js).
-- Por eso aquí se insertan los IDs de forma EXPLÍCITA.
-- =====================================================

-- Limpieza defensiva por si ya había datos parciales de una corrida anterior.
DELETE FROM detalle_producto_motivo;
DELETE FROM detalle_producto_compra;
DELETE FROM detalle_producto;
DELETE FROM motivo_denuncia;
DELETE FROM tipo_producto;
DELETE FROM area WHERE codigo_area = 'TEMP';
COMMIT;

INSERT INTO region (nombre) VALUES ('Central');

-- Área temporal: NO es una área real del Ministerio, es solo
-- para que el SP tenga algo que asignar mientras HU-008
-- (matching real ubicacion -> area) no está lista.
-- TODO(HU-008): eliminar esta área temporal cuando exista
-- el import real del Excel de ubicacion_area.
INSERT INTO area (nombre, tipo, codigo_area, region_id)
VALUES ('Área Temporal (pendiente asignar - HU-008)', 'AR', 'TEMP', 1);

-- tipo_producto: mismo orden/ID que TIPOS_PRODUCTO_MAP en denunciaService.js
INSERT INTO tipo_producto (id_tipo_producto, nombre) VALUES (1, 'Medicamento');
INSERT INTO tipo_producto (id_tipo_producto, nombre) VALUES (2, 'Cosmético');
INSERT INTO tipo_producto (id_tipo_producto, nombre) VALUES (3, 'Alimento');
INSERT INTO tipo_producto (id_tipo_producto, nombre) VALUES (4, 'Dispositivo médico');

-- motivo_denuncia: mismo orden/ID que MOTIVOS_MAP en denunciaService.js
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (1, 'Etiqueta muestra indicaciones no aprobadas en el registro sanitario');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (2, 'Etiqueta no indica el número de registro sanitario (no aplica para cosméticos)');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (3, 'Etiqueta sin número de lote, fecha de vencimiento, fabricante');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (4, 'Mal estado de productos (defectuoso, contaminado, deteriorado)');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (5, 'Producto bajo alerta sanitaria');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (6, 'Producto con problema de calidad');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (7, 'Producto para modalidad de venta en sitios no autorizados');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (8, 'Producto sin registro sanitario');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (9, 'Publicidad engañosa');
INSERT INTO motivo_denuncia (id_motivo, nombre) VALUES (10, 'Sospecha de producto falsificado o adulterado');

-- Empuja el contador del IDENTITY para que, si en el futuro alguien
-- inserta un tipo_producto/motivo nuevo SIN especificar id, no choque
-- con estos 4 / 10 que ya dejamos fijos.
ALTER TABLE tipo_producto MODIFY id_tipo_producto
  GENERATED BY DEFAULT AS IDENTITY (START WITH 100);
ALTER TABLE motivo_denuncia MODIFY id_motivo
  GENERATED BY DEFAULT AS IDENTITY (START WITH 100);

COMMIT;
