-- =====================================================
-- CATÁLOGOS BASE
-- =====================================================

CREATE TABLE denunciante (
  id_denunciante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR2(150),
  correo         VARCHAR2(150),
  telefono       VARCHAR2(20)
);
-- atributos propios: 3

CREATE TABLE tipo_producto (
  id_tipo_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR2(100) NOT NULL,
  activo           CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);
-- atributos propios: 2

CREATE TABLE producto (
  id_producto      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR2(200) NOT NULL,
  tipo_producto_id NUMBER,
  activo           CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
  CONSTRAINT FK_PRODUCTO_TIPO_PRODUCTO FOREIGN KEY (tipo_producto_id) REFERENCES tipo_producto(id_tipo_producto)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_PRODUCTO_TIPO_PRODUCTO_ID ON producto(tipo_producto_id);

-- atributos propios: 2

CREATE TABLE region (
  id_region NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    VARCHAR2(100) NOT NULL
);
-- atributos propios: 1

CREATE TABLE area (
  id_area     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(150) NOT NULL,
  tipo        VARCHAR2(10) CHECK (tipo IN ('ARS','AR','UVC')),
  codigo_area VARCHAR2(20) NOT NULL,
  region_id   NUMBER,
  CONSTRAINT FK_AREA_REGION FOREIGN KEY (region_id) REFERENCES region(id_region)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_AREA_REGION_ID ON area(region_id);

-- atributos propios: 3

CREATE TABLE funcionario (
  id_funcionario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR2(150) NOT NULL,
  rol            VARCHAR2(30) CHECK (rol IN ('validador','jefe_area','superusuario')),
  correo         VARCHAR2(150),
  area_id        NUMBER NOT NULL,
  activo         CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
  CONSTRAINT FK_FUNCIONARIO_AREA FOREIGN KEY (area_id) REFERENCES area(id_area)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_FUNCIONARIO_AREA_ID ON funcionario(area_id);

-- atributos propios: 4

CREATE TABLE criterio (
  id_criterio     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR2(150) NOT NULL,
  tipo_respuesta  VARCHAR2(30) NOT NULL,
  activo          CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);
-- atributos propios: 4
-- Datos esperados (2 criterios puntuables, fórmula confirmada = suma simple, máx 6):
--   'Daño potencial a la salud'          (Bajo=1 / Medio=3 / Alto=5)
--   'Criterio técnico especializado UVC' (No=0 / Sí=1)
-- "Comercio electrónico" NO es un criterio puntuable, ver evaluacion_criticidad.
CREATE TABLE criterio_valor (
  id_criterio NUMBER NOT NULL,
  valor       VARCHAR2(50) NOT NULL,
  puntaje     NUMBER(5,2) NOT NULL,
  CONSTRAINT PK_CRITERIO_VALOR PRIMARY KEY (id_criterio, valor),
  CONSTRAINT FK_CRITERIO_VALOR_CRITERIO FOREIGN KEY (id_criterio) REFERENCES criterio(id_criterio)
);
-- atributos propios: 1

CREATE TABLE nivel_criticidad (
  nivel       VARCHAR2(20) PRIMARY KEY,
  puntaje_min NUMBER(5,2) NOT NULL,
  puntaje_max NUMBER(5,2) NOT NULL,
  plazo_dias  NUMBER NOT NULL
);
-- atributos propios: 3
-- Rangos confirmados: ALTO 5-6 (60 días) | MEDIO 3-4 (90 días) | BAJO 1-2 (120 días)

-- =====================================================
-- UBICACIÓN GEOGRÁFICA
-- =====================================================

CREATE TABLE provincia (
  id_provincia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(100) NOT NULL
);
-- atributos propios: 1

CREATE TABLE canton (
  id_canton      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provincia_id   NUMBER NOT NULL,
  nombre         VARCHAR2(100) NOT NULL,
  tiene_distrito CHAR(1) DEFAULT 'N' CHECK (tiene_distrito IN ('S','N')),
  CONSTRAINT FK_CANTON_PROVINCIA FOREIGN KEY (provincia_id) REFERENCES provincia(id_provincia)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_CANTON_PROVINCIA_ID ON canton(provincia_id);

-- atributos propios: 2

CREATE TABLE distrito (
  id_distrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canton_id   NUMBER NOT NULL,
  nombre      VARCHAR2(100) NOT NULL,
  CONSTRAINT FK_DISTRITO_CANTON FOREIGN KEY (canton_id) REFERENCES canton(id_canton)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DISTRITO_CANTON_ID ON distrito(canton_id);

-- atributos propios: 1

CREATE TABLE ubicacion_area (
  id_ubicacion_area NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canton_id         NUMBER NOT NULL,
  distrito_id       NUMBER,
  area_id           NUMBER NOT NULL,
  CONSTRAINT FK_UBICACION_CANTON FOREIGN KEY (canton_id) REFERENCES canton(id_canton),
  CONSTRAINT FK_UBICACION_DISTRITO FOREIGN KEY (distrito_id) REFERENCES distrito(id_distrito),
  CONSTRAINT FK_UBICACION_AREA FOREIGN KEY (area_id) REFERENCES area(id_area)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_UBICACION_AREA_CANTON_ID ON ubicacion_area(canton_id);
CREATE INDEX IDX_UBICACION_AREA_DISTRITO_ID ON ubicacion_area(distrito_id);
CREATE INDEX IDX_UBICACION_AREA_AREA_ID ON ubicacion_area(area_id);

-- atributos propios: 0

-- =====================================================
-- ALERTAS SANITARIAS
-- =====================================================

CREATE TABLE alerta_sanitaria (
  id_alerta          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_alerta      VARCHAR2(20),
  fecha_publicacion  DATE,
  tipo_advertencia   VARCHAR2(20) CHECK (tipo_advertencia IN ('producto_especifico','categoria_general')),
  registro_sanitario VARCHAR2(30),
  marca              VARCHAR2(150),
  fabricante         VARCHAR2(200)
);
-- atributos propios: 6 (en el límite)

CREATE TABLE alerta_sanitaria_producto (
  alerta_id   NUMBER NOT NULL,
  producto_id NUMBER NOT NULL,
  activa      CHAR(1) DEFAULT 'S' CHECK (activa IN ('S','N')),
  CONSTRAINT PK_ALERTA_PRODUCTO PRIMARY KEY (alerta_id, producto_id),
  CONSTRAINT FK_ALERTA_PROD_ALERTA FOREIGN KEY (alerta_id) REFERENCES alerta_sanitaria(id_alerta),
  CONSTRAINT FK_ALERTA_PROD_PRODUCTO FOREIGN KEY (producto_id) REFERENCES producto(id_producto)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_ALERTA_SANITARIA_PRODUCTO_PRODUCTO_ID ON alerta_sanitaria_producto(producto_id);

-- atributos propios: 1

-- =====================================================
-- MOTIVO DE LA DENUNCIA
-- =====================================================

CREATE TABLE motivo_denuncia (
  id_motivo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    VARCHAR2(200) NOT NULL,
  activo    CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);
-- atributos propios: 2

-- =====================================================
-- DENUNCIA (núcleo)
-- =====================================================

CREATE TABLE denuncia (
  id_denuncia              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consecutivo              VARCHAR2(60),
  numero_secuencial        NUMBER NOT NULL,
  estado                   VARCHAR2(20) DEFAULT 'PENDIENTE_ASIGNACION'
                            CONSTRAINT CK_DENUNCIA_ESTADO CHECK (estado IN (
                              'PENDIENTE_ASIGNACION','EN_TIEMPO','PRONTA_VENCER',
                              'ATRASADA','EN_REVISION','FINALIZADA')),
  fecha_creacion           DATE DEFAULT SYSDATE NOT NULL,
  area_actual_id           NUMBER NOT NULL,
  funcionario_asignado_id  NUMBER,
  carpeta_confidencial_url    VARCHAR2(500),
  carpeta_no_confidencial_url VARCHAR2(500),
  CONSTRAINT UQ_DENUNCIA_CONSECUTIVO UNIQUE (consecutivo),
  CONSTRAINT UQ_DENUNCIA_AREA_SEC UNIQUE (area_actual_id, numero_secuencial),
  CONSTRAINT FK_DENUNCIA_AREA_ACTUAL FOREIGN KEY (area_actual_id) REFERENCES area(id_area),
  CONSTRAINT FK_DENUNCIA_FUNC_ASIGNADO FOREIGN KEY (funcionario_asignado_id) REFERENCES funcionario(id_funcionario)
);

CREATE INDEX IDX_DENUNCIA_AREA_ACTUAL_ID ON denuncia(area_actual_id);
CREATE INDEX IDX_DENUNCIA_FUNCIONARIO_ASIGNADO_ID ON denuncia(funcionario_asignado_id);

-- atributos propios: 6 (consecutivo, numero_secuencial, estado, fecha_creacion,
--                       carpeta_confidencial_url, carpeta_no_confidencial_url) -> en el límite
-- funcionario_asignado_id = "funcionario encargado" (HU-013), quien trabaja y cierra el caso.
-- El funcionario validador (HU-010/011) queda registrado en evaluacion_criticidad, no aquí,
-- porque puede haber más de una evaluación en el tiempo (re-evaluaciones).

CREATE TABLE denuncia_hecho (
  denuncia_id                      NUMBER PRIMARY KEY,
  nombre_establecimiento           VARCHAR2(200) NOT NULL,
  descripcion_hecho                VARCHAR2(4000) NOT NULL,
  denunciado_otra_institucion      CHAR(1) CHECK (denunciado_otra_institucion IN ('S','N')),
  detalle_otra_institucion         VARCHAR2(500),
  denunciado_previamente_minsalud  CHAR(1) CHECK (denunciado_previamente_minsalud IN ('S','N')),
  detalle_previo_minsalud          VARCHAR2(500),
  CONSTRAINT FK_DEN_HECHO_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia)
);
-- atributos propios: 6 (en el límite) -- NUEVA

CREATE TABLE denuncia_ubicacion (
  denuncia_id          NUMBER PRIMARY KEY,
  canton_id            NUMBER NOT NULL,
  distrito_id          NUMBER,
  area_formulario_id   NUMBER NOT NULL,
  direccion_exacta     VARCHAR2(500),
  CONSTRAINT FK_DEN_UBIC_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_DEN_UBIC_CANTON FOREIGN KEY (canton_id) REFERENCES canton(id_canton),
  CONSTRAINT FK_DEN_UBIC_DISTRITO FOREIGN KEY (distrito_id) REFERENCES distrito(id_distrito),
  CONSTRAINT FK_DEN_UBIC_AREA_FORM FOREIGN KEY (area_formulario_id) REFERENCES area(id_area)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DENUNCIA_UBICACION_CANTON_ID ON denuncia_ubicacion(canton_id);
CREATE INDEX IDX_DENUNCIA_UBICACION_DISTRITO_ID ON denuncia_ubicacion(distrito_id);
CREATE INDEX IDX_DENUNCIA_UBICACION_AREA_FORMULARIO_ID ON denuncia_ubicacion(area_formulario_id);

-- atributos propios: 1 (direccion_exacta)

CREATE TABLE denuncia_denunciante (
  denuncia_id         NUMBER PRIMARY KEY,
  denunciante_id      NUMBER,
  es_anonima          CHAR(1) DEFAULT 'N' CHECK (es_anonima IN ('S','N')),
  direccion_domicilio VARCHAR2(500),
  CONSTRAINT FK_DEN_DENUNCIANTE_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_DEN_DENUNCIANTE_DENUNCIANTE FOREIGN KEY (denunciante_id) REFERENCES denunciante(id_denunciante)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DENUNCIA_DENUNCIANTE_DENUNCIANTE_ID ON denuncia_denunciante(denunciante_id);

-- atributos propios: 2

-- =====================================================
-- PRODUCTO(S) DENUNCIADO(S) -- ahora 1:N real con denuncia
-- =====================================================

CREATE TABLE detalle_producto (
  id_detalle_producto           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denuncia_id                   NUMBER NOT NULL,
  producto_id                   NUMBER,
  tipo_producto_id              NUMBER,
  nombre_producto_texto         VARCHAR2(200) NOT NULL,
  registro_sanitario_ingresado  VARCHAR2(30),
  descripcion_producto          VARCHAR2(500) NOT NULL,
  marca_ingresada               VARCHAR2(150),
  CONSTRAINT FK_DETPROD_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_DETPROD_PRODUCTO FOREIGN KEY (producto_id) REFERENCES producto(id_producto),
  CONSTRAINT FK_DETPROD_TIPO_PRODUCTO FOREIGN KEY (tipo_producto_id) REFERENCES tipo_producto(id_tipo_producto)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DETALLE_PRODUCTO_DENUNCIA_ID ON detalle_producto(denuncia_id);
CREATE INDEX IDX_DETALLE_PRODUCTO_PRODUCTO_ID ON detalle_producto(producto_id);
CREATE INDEX IDX_DETALLE_PRODUCTO_TIPO_PRODUCTO_ID ON detalle_producto(tipo_producto_id);

-- atributos propios: 4 (nombre_producto_texto, registro_sanitario_ingresado,
--                       descripcion_producto, marca_ingresada)

CREATE TABLE detalle_producto_compra (
  id_detalle_producto  NUMBER PRIMARY KEY,
  numero_lote          VARCHAR2(50),
  fabricante_ingresado VARCHAR2(200),
  pais_origen          VARCHAR2(100),
  presentacion         VARCHAR2(100),
  fecha_compra         DATE,
  CONSTRAINT FK_DETPRODCOMPRA_DETPROD FOREIGN KEY (id_detalle_producto) REFERENCES detalle_producto(id_detalle_producto)
);
-- atributos propios: 5 -- NUEVA (datos secundarios del Apartado IV, 1:1 con detalle_producto)

CREATE TABLE detalle_producto_motivo (
  id_detalle_producto NUMBER NOT NULL,
  id_motivo            NUMBER NOT NULL,
  CONSTRAINT PK_DETPROD_MOTIVO PRIMARY KEY (id_detalle_producto, id_motivo),
  CONSTRAINT FK_DPM_DETPROD FOREIGN KEY (id_detalle_producto) REFERENCES detalle_producto(id_detalle_producto),
  CONSTRAINT FK_DPM_MOTIVO FOREIGN KEY (id_motivo) REFERENCES motivo_denuncia(id_motivo)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DETALLE_PRODUCTO_MOTIVO_ID_MOTIVO ON detalle_producto_motivo(id_motivo);

-- atributos propios: 0 -- NUEVA, reemplaza a denuncia_motivo (motivos POR PRODUCTO)

-- =====================================================
-- CRITICIDAD
-- =====================================================

CREATE TABLE evaluacion_criticidad (
  id_evaluacion                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denuncia_id                     NUMBER NOT NULL,
  funcionario_validador_id        NUMBER NOT NULL,
  fecha_evaluacion                DATE DEFAULT SYSDATE NOT NULL,
  nivel_criticidad                VARCHAR2(20),
  puntaje_total                   NUMBER(6,2),
  vinculado_comercio_electronico  CHAR(1) CHECK (vinculado_comercio_electronico IN ('S','N')),
  fecha_limite                    DATE,
  CONSTRAINT FK_EVAL_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_EVAL_FUNCIONARIO FOREIGN KEY (funcionario_validador_id) REFERENCES funcionario(id_funcionario),
  CONSTRAINT FK_EVAL_NIVEL FOREIGN KEY (nivel_criticidad) REFERENCES nivel_criticidad(nivel)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_EVALUACION_CRITICIDAD_DENUNCIA_ID ON evaluacion_criticidad(denuncia_id);
CREATE INDEX IDX_EVALUACION_CRITICIDAD_FUNCIONARIO_VALIDADOR_ID ON evaluacion_criticidad(funcionario_validador_id);
CREATE INDEX IDX_EVALUACION_CRITICIDAD_NIVEL_CRITICIDAD ON evaluacion_criticidad(nivel_criticidad);

-- atributos propios: 4 (fecha_evaluacion, puntaje_total, vinculado_comercio_electronico, fecha_limite)

CREATE TABLE respuesta_criterio (
  id_evaluacion       NUMBER NOT NULL,
  criterio_id         NUMBER NOT NULL,
  valor_seleccionado  VARCHAR2(50) NOT NULL,
  puntaje_obtenido    NUMBER(5,2) NOT NULL,
  CONSTRAINT PK_RESPUESTA_CRITERIO PRIMARY KEY (id_evaluacion, criterio_id),
  CONSTRAINT FK_RESP_CRITERIO_EVAL FOREIGN KEY (id_evaluacion) REFERENCES evaluacion_criticidad(id_evaluacion),
  CONSTRAINT FK_RESP_CRITERIO_VALOR FOREIGN KEY (criterio_id, valor_seleccionado)
      REFERENCES criterio_valor(id_criterio, valor)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_RESPUESTA_CRITERIO_CRITERIO_VALOR ON respuesta_criterio(criterio_id, valor_seleccionado);

-- atributos propios: 2

CREATE TABLE denuncia_cierre (
  denuncia_id          NUMBER PRIMARY KEY,
  aprobado_por_jefe_id NUMBER,
  fecha_finalizacion   DATE,
  CONSTRAINT FK_DEN_CIERRE_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_DEN_CIERRE_JEFE FOREIGN KEY (aprobado_por_jefe_id) REFERENCES funcionario(id_funcionario)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_DENUNCIA_CIERRE_APROBADO_POR_JEFE_ID ON denuncia_cierre(aprobado_por_jefe_id);

-- atributos propios: 1

-- =====================================================
-- SEGUIMIENTO
-- =====================================================

CREATE TABLE bitacora (
  id_bitacora       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denuncia_id       NUMBER,
  funcionario_id    NUMBER NOT NULL,
  area_origen_id    NUMBER,
  fecha             DATE DEFAULT SYSDATE NOT NULL,
  tipo_registro     VARCHAR2(20) CHECK (tipo_registro IN ('accion_obligatoria','accion_opcional','consulta','solicitud_traslado','informacion_adicional')),
  carpeta           VARCHAR2(20) CHECK (carpeta IN ('confidencial','no_confidencial')),
  contenido         VARCHAR2(2000),
  estado_aprobacion VARCHAR2(20) CHECK (estado_aprobacion IN ('pendiente','aprobada','rechazada')),
  CONSTRAINT FK_BITACORA_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_BITACORA_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES funcionario(id_funcionario),
  CONSTRAINT FK_BITACORA_AREA_ORIGEN FOREIGN KEY (area_origen_id) REFERENCES area(id_area)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_BITACORA_DENUNCIA_ID ON bitacora(denuncia_id);
CREATE INDEX IDX_BITACORA_FUNCIONARIO_ID ON bitacora(funcionario_id);
CREATE INDEX IDX_BITACORA_AREA_ORIGEN_ID ON bitacora(area_origen_id);

-- atributos propios: 6 (en el límite)

CREATE TABLE notificacion (
  id_notificacion             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denuncia_id                 NUMBER NOT NULL,
  tipo                        VARCHAR2(30),
  destinatario_tipo           VARCHAR2(20) CHECK (destinatario_tipo IN ('funcionario','jefe_area','superusuario','denunciante')),
  destinatario_funcionario_id NUMBER,
  fecha                       DATE DEFAULT SYSDATE NOT NULL,
  mensaje                     VARCHAR2(1000),
  CONSTRAINT FK_NOTIF_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_NOTIF_FUNCIONARIO FOREIGN KEY (destinatario_funcionario_id) REFERENCES funcionario(id_funcionario)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_NOTIFICACION_DENUNCIA_ID ON notificacion(denuncia_id);
CREATE INDEX IDX_NOTIFICACION_DESTINATARIO_FUNCIONARIO_ID ON notificacion(destinatario_funcionario_id);

-- atributos propios: 5

CREATE TABLE historial_asignacion (
  id_historial            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denuncia_id             NUMBER NOT NULL,
  area_anterior_id        NUMBER,
  area_nueva_id           NUMBER NOT NULL,
  funcionario_anterior_id NUMBER,
  funcionario_nuevo_id    NUMBER,
  realizado_por_id        NUMBER NOT NULL,
  fecha                   DATE DEFAULT SYSDATE NOT NULL,
  motivo                  VARCHAR2(500),
  CONSTRAINT FK_HIST_DENUNCIA FOREIGN KEY (denuncia_id) REFERENCES denuncia(id_denuncia),
  CONSTRAINT FK_HIST_AREA_ANT FOREIGN KEY (area_anterior_id) REFERENCES area(id_area),
  CONSTRAINT FK_HIST_AREA_NUEVA FOREIGN KEY (area_nueva_id) REFERENCES area(id_area),
  CONSTRAINT FK_HIST_FUNC_ANT FOREIGN KEY (funcionario_anterior_id) REFERENCES funcionario(id_funcionario),
  CONSTRAINT FK_HIST_FUNC_NUEVO FOREIGN KEY (funcionario_nuevo_id) REFERENCES funcionario(id_funcionario),
  CONSTRAINT FK_HIST_REALIZADO_POR FOREIGN KEY (realizado_por_id) REFERENCES funcionario(id_funcionario)
);
-- Índices (B04 -- obligatorios en toda columna FK):
CREATE INDEX IDX_HISTORIAL_ASIGNACION_DENUNCIA_ID ON historial_asignacion(denuncia_id);
CREATE INDEX IDX_HISTORIAL_ASIGNACION_AREA_ANTERIOR_ID ON historial_asignacion(area_anterior_id);
CREATE INDEX IDX_HISTORIAL_ASIGNACION_AREA_NUEVA_ID ON historial_asignacion(area_nueva_id);
CREATE INDEX IDX_HISTORIAL_ASIGNACION_FUNCIONARIO_ANTERIOR_ID ON historial_asignacion(funcionario_anterior_id);
CREATE INDEX IDX_HISTORIAL_ASIGNACION_FUNCIONARIO_NUEVO_ID ON historial_asignacion(funcionario_nuevo_id);
CREATE INDEX IDX_HISTORIAL_ASIGNACION_REALIZADO_POR_ID ON historial_asignacion(realizado_por_id);

-- numero_identificacion en denunciante
ALTER TABLE denunciante ADD (numero_identificacion VARCHAR2(30));

-- NOT NULL en es_anonima
ALTER TABLE denuncia_denunciante MODIFY (es_anonima NOT NULL);

-- bitacora.funcionario_id nullable (NULL = accion automatica del sistema)
ALTER TABLE bitacora MODIFY (funcionario_id NULL);

-- consecutivo mas ancho: codigo_area (hasta 20) + '-' + anio (4) + '-' + secuencial (6)
-- puede llegar a superar los 30 caracteres originales
ALTER TABLE denuncia MODIFY (consecutivo VARCHAR2(60));
-- =====================================================
-- CAMBIOS DE ESQUEMA: tipo_producto obligatorio (punto 2)
-- y consecutivo con reinicio anual (punto 3)
-- =====================================================

-- Punto 2: tipo_producto_id pasa a ser obligatorio a nivel de tabla
ALTER TABLE detalle_producto MODIFY (tipo_producto_id NOT NULL);

-- Punto 3a: el contador ahora es por (area_id, anio), no solo por area_id
ALTER TABLE contador_denuncia_area ADD anio NUMBER(4);

-- Punto 3b: denuncia necesita el anio como parte de la clave de unicidad,
-- porque el numero_secuencial ahora se repite entre anios distintos.
ALTER TABLE denuncia ADD anio_creacion NUMBER(4);

ALTER TABLE denuncia DROP CONSTRAINT UQ_DENUNCIA_AREA_SEC;
ALTER TABLE denuncia
  ADD CONSTRAINT UQ_DENUNCIA_AREA_SEC UNIQUE (area_actual_id, anio_creacion, numero_secuencial);

-- Retorna 'S' si el texto no esta vacio, no es solo puntuacion/espacios
-- y tiene al menos p_min_longitud caracteres.
CREATE OR REPLACE FUNCTION fn_texto_valido (
  p_texto        IN VARCHAR2,
  p_min_longitud IN NUMBER DEFAULT 3
) RETURN CHAR
IS
  v_texto VARCHAR2(4000);
BEGIN
  v_texto := TRIM(p_texto);

  IF v_texto IS NULL THEN
    RETURN 'N';
  END IF;

  IF LENGTH(v_texto) < p_min_longitud THEN
    RETURN 'N';
  END IF;

  -- exige que haya al menos un caracter alfanumerico (descarta "..." o "   ")
  IF NOT REGEXP_LIKE(v_texto, '[[:alnum:]]') THEN
    RETURN 'N';
  END IF;

  RETURN 'S';
END fn_texto_valido;
/

CREATE TABLE contador_denuncia_area (
  area_id       NUMBER NOT NULL,
  anio          NUMBER(4) NOT NULL,
  ultimo_numero NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT PK_CONTADOR_AREA PRIMARY KEY (area_id, anio),
  CONSTRAINT FK_CONTADOR_AREA FOREIGN KEY (area_id) REFERENCES area(id_area)
);

-- cada vez que se crea un area, se le siembra su contador en 0
-- para que sp_registrar_denuncia nunca dependa de un INSERT concurrente
CREATE OR REPLACE TRIGGER trg_area_ai
AFTER INSERT ON area
FOR EACH ROW
BEGIN
  INSERT INTO contador_denuncia_area (area_id, ultimo_numero)
  VALUES (:NEW.id_area, 0);
END trg_area_ai;
/

CREATE OR REPLACE PROCEDURE sp_registrar_denuncia (
  p_denuncia_json IN  CLOB,
  p_id_denuncia   OUT NUMBER,
  p_consecutivo   OUT VARCHAR2
)
IS
  -- datos del hecho
  v_denunciado_otra_institucion     denuncia_hecho.denunciado_otra_institucion%TYPE;
  v_detalle_otra_institucion        denuncia_hecho.detalle_otra_institucion%TYPE;
  v_denunciado_previamente_minsalud denuncia_hecho.denunciado_previamente_minsalud%TYPE;
  v_detalle_previo_minsalud         denuncia_hecho.detalle_previo_minsalud%TYPE;
  v_nombre_establecimiento          denuncia_hecho.nombre_establecimiento%TYPE;
  v_descripcion_hecho               denuncia_hecho.descripcion_hecho%TYPE;

  -- ubicacion
  v_canton_id        canton.id_canton%TYPE;
  v_distrito_id      distrito.id_distrito%TYPE;
  v_direccion_exacta denuncia_ubicacion.direccion_exacta%TYPE;
  v_tiene_distrito   canton.tiene_distrito%TYPE;

  -- privacidad / denunciante
  v_es_anonima         denuncia_denunciante.es_anonima%TYPE;
  v_den_nombre         denunciante.nombre%TYPE;
  v_den_numero_id      denunciante.numero_identificacion%TYPE;
  v_den_correo         denunciante.correo%TYPE;
  v_den_telefono       denunciante.telefono%TYPE;
  v_den_direccion      denuncia_denunciante.direccion_domicilio%TYPE;
  v_denunciante_id     denunciante.id_denunciante%TYPE;

  -- area / consecutivo
  v_area_id           area.id_area%TYPE;
  v_codigo_area       area.codigo_area%TYPE;
  v_anio              NUMBER(4);
  v_numero_secuencial denuncia.numero_secuencial%TYPE;

  -- productos
  v_id_detalle_producto detalle_producto.id_detalle_producto%TYPE;
  v_num_productos        NUMBER := 0;
  v_num_motivos           NUMBER := 0;

BEGIN
  ----------------------------------------------------------------
  -- 0. validacion basica del payload
  ----------------------------------------------------------------
  IF p_denuncia_json IS NULL OR NOT p_denuncia_json IS JSON THEN
    RAISE_APPLICATION_ERROR(-20000, 'El payload de la denuncia no es un JSON valido.');
  END IF;

  ----------------------------------------------------------------
  -- 1. leer campos escalares del JSON
  ----------------------------------------------------------------
  SELECT jt.denunciado_otra_institucion,
         jt.detalle_otra_institucion,
         jt.denunciado_previamente_minsalud,
         jt.detalle_previo_minsalud,
         jt.nombre_establecimiento,
         jt.descripcion_hecho,
         jt.canton_id,
         jt.distrito_id,
         jt.direccion_exacta,
         jt.es_anonima,
         jt.denunciante_nombre,
         jt.denunciante_numero_identificacion,
         jt.denunciante_correo,
         jt.denunciante_telefono,
         jt.denunciante_direccion_domicilio
    INTO v_denunciado_otra_institucion,
         v_detalle_otra_institucion,
         v_denunciado_previamente_minsalud,
         v_detalle_previo_minsalud,
         v_nombre_establecimiento,
         v_descripcion_hecho,
         v_canton_id,
         v_distrito_id,
         v_direccion_exacta,
         v_es_anonima,
         v_den_nombre,
         v_den_numero_id,
         v_den_correo,
         v_den_telefono,
         v_den_direccion
    FROM JSON_TABLE(
      p_denuncia_json, '$'
      COLUMNS (
        denunciado_otra_institucion      CHAR(1)       PATH '$.hecho.denunciado_otra_institucion',
        detalle_otra_institucion         VARCHAR2(500) PATH '$.hecho.detalle_otra_institucion',
        denunciado_previamente_minsalud  CHAR(1)       PATH '$.hecho.denunciado_previamente_minsalud',
        detalle_previo_minsalud          VARCHAR2(500) PATH '$.hecho.detalle_previo_minsalud',
        nombre_establecimiento           VARCHAR2(200) PATH '$.hecho.nombre_establecimiento',
        descripcion_hecho                VARCHAR2(4000) PATH '$.hecho.descripcion_hecho',
        canton_id                        NUMBER        PATH '$.ubicacion.canton_id',
        distrito_id                      NUMBER        PATH '$.ubicacion.distrito_id',
        direccion_exacta                 VARCHAR2(500) PATH '$.ubicacion.direccion_exacta',
        es_anonima                       CHAR(1)       PATH '$.privacidad.es_anonima',
        denunciante_nombre               VARCHAR2(150) PATH '$.privacidad.denunciante.nombre',
        denunciante_numero_identificacion VARCHAR2(30) PATH '$.privacidad.denunciante.numero_identificacion',
        denunciante_correo               VARCHAR2(150) PATH '$.privacidad.denunciante.correo',
        denunciante_telefono             VARCHAR2(20)  PATH '$.privacidad.denunciante.telefono',
        denunciante_direccion_domicilio  VARCHAR2(500) PATH '$.privacidad.denunciante.direccion_domicilio'
      )
    ) jt;

  -- normalizar blancos a NULL (regla general HU-002)
  v_detalle_otra_institucion := NULLIF(TRIM(v_detalle_otra_institucion), '');
  v_detalle_previo_minsalud  := NULLIF(TRIM(v_detalle_previo_minsalud), '');
  v_direccion_exacta         := NULLIF(TRIM(v_direccion_exacta), '');
  v_den_correo               := NULLIF(TRIM(v_den_correo), '');
  v_den_telefono              := NULLIF(TRIM(v_den_telefono), '');
  v_den_direccion             := NULLIF(TRIM(v_den_direccion), '');

  ----------------------------------------------------------------
  -- 2. validaciones de campos obligatorios (HU-002)
  ----------------------------------------------------------------
  IF fn_texto_valido(v_nombre_establecimiento) = 'N' THEN
    RAISE_APPLICATION_ERROR(-20001, 'El nombre del establecimiento o persona a denunciar es obligatorio.');
  END IF;

  IF fn_texto_valido(v_descripcion_hecho, 10) = 'N' THEN
    RAISE_APPLICATION_ERROR(-20002, 'La descripcion cronologica de la problematica es obligatoria.');
  END IF;

  -- PUNTO 1: se agrega "IS NULL OR" para que un campo ausente
  -- se rechace explicitamente, en vez de colar silenciosamente al ELSE
  -- (rama confidencial) mas abajo.
  IF v_es_anonima IS NULL OR v_es_anonima NOT IN ('S','N') THEN
    RAISE_APPLICATION_ERROR(-20003, 'Debe indicar si la denuncia es anonima o confidencial.');
  END IF;

  IF v_es_anonima = 'S' THEN
    -- anonima: no se piden ni se guardan datos del denunciante
    v_den_nombre    := NULL;
    v_den_numero_id := NULL;
    v_den_correo    := NULL;
    v_den_telefono  := NULL;
    v_den_direccion := NULL;
  ELSE
    -- confidencial: nombre y numero de identificacion son obligatorios
    IF fn_texto_valido(v_den_nombre) = 'N' THEN
      RAISE_APPLICATION_ERROR(-20004, 'El nombre del denunciante es obligatorio en denuncia confidencial.');
    END IF;
    IF fn_texto_valido(v_den_numero_id) = 'N' THEN
      RAISE_APPLICATION_ERROR(-20005, 'El numero de identificacion del denunciante es obligatorio en denuncia confidencial.');
    END IF;
  END IF;

  ----------------------------------------------------------------
  -- 3. resolver canton / distrito
  ----------------------------------------------------------------
  BEGIN
    SELECT tiene_distrito INTO v_tiene_distrito
    FROM canton WHERE id_canton = v_canton_id;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20006, 'El canton indicado no existe.');
  END;

  IF v_tiene_distrito = 'S' AND v_distrito_id IS NULL THEN
    RAISE_APPLICATION_ERROR(-20007, 'Debe indicar el distrito para el canton seleccionado.');
  ELSIF v_tiene_distrito = 'N' THEN
    v_distrito_id := NULL; -- este canton no maneja distrito
  END IF;

  ----------------------------------------------------------------
  -- 4. resolver area (HU-009: busqueda deterministica, siempre hay match)
  ----------------------------------------------------------------
  BEGIN
    SELECT area_id INTO v_area_id
    FROM ubicacion_area
    WHERE canton_id = v_canton_id
      AND NVL(distrito_id, -1) = NVL(v_distrito_id, -1)
      AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20008, 'No se encontro un area asociada a la ubicacion indicada.');
  END;

  SELECT codigo_area INTO v_codigo_area FROM area WHERE id_area = v_area_id;

  ----------------------------------------------------------------
  -- 5. numero secuencial por area Y ANIO (PUNTO 3: reinicio anual)
  ----------------------------------------------------------------
  v_anio := TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'));

  -- crea la fila (area, anio) si es la primera denuncia de esa area en el anio
  BEGIN
    INSERT INTO contador_denuncia_area (area_id, anio, ultimo_numero)
    VALUES (v_area_id, v_anio, 0);
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      NULL; -- ya existia, seguimos al UPDATE
  END;

  UPDATE contador_denuncia_area
     SET ultimo_numero = ultimo_numero + 1
   WHERE area_id = v_area_id AND anio = v_anio
  RETURNING ultimo_numero INTO v_numero_secuencial;

  p_consecutivo := v_codigo_area || '-' || TO_CHAR(v_anio) || '-' ||
                   LPAD(v_numero_secuencial, 6, '0');

  ----------------------------------------------------------------
  -- 6. denuncia (id, area, anio, secuencial, consecutivo, estado por DEFAULT)
  ----------------------------------------------------------------
  INSERT INTO denuncia (consecutivo, numero_secuencial, anio_creacion, area_actual_id)
  VALUES (p_consecutivo, v_numero_secuencial, v_anio, v_area_id)
  RETURNING id_denuncia INTO p_id_denuncia;

  INSERT INTO denuncia_hecho (
    denuncia_id, nombre_establecimiento, descripcion_hecho,
    denunciado_otra_institucion, detalle_otra_institucion,
    denunciado_previamente_minsalud, detalle_previo_minsalud
  ) VALUES (
    p_id_denuncia, v_nombre_establecimiento, v_descripcion_hecho,
    v_denunciado_otra_institucion, v_detalle_otra_institucion,
    v_denunciado_previamente_minsalud, v_detalle_previo_minsalud
  );

  INSERT INTO denuncia_ubicacion (
    denuncia_id, canton_id, distrito_id, area_formulario_id, direccion_exacta
  ) VALUES (
    p_id_denuncia, v_canton_id, v_distrito_id, v_area_id, v_direccion_exacta
  );

  ----------------------------------------------------------------
  -- 7. denunciante (solo si es confidencial)
  ----------------------------------------------------------------
  IF v_es_anonima = 'N' THEN
    INSERT INTO denunciante (nombre, numero_identificacion, correo, telefono)
    VALUES (v_den_nombre, v_den_numero_id, v_den_correo, v_den_telefono)
    RETURNING id_denunciante INTO v_denunciante_id;
  END IF;

  INSERT INTO denuncia_denunciante (denuncia_id, denunciante_id, es_anonima, direccion_domicilio)
  VALUES (p_id_denuncia, v_denunciante_id, v_es_anonima, v_den_direccion);

  ----------------------------------------------------------------
  -- 8. productos (uno o varios) y sus motivos
  ----------------------------------------------------------------
  FOR prod IN (
    SELECT jt.rn, jt.tipo_producto_id, jt.nombre_producto_texto,
           jt.registro_sanitario_ingresado, jt.descripcion_producto,
           jt.marca_ingresada, jt.numero_lote, jt.fabricante_ingresado,
           jt.pais_origen, jt.presentacion, jt.fecha_compra_txt, jt.motivos_json
    FROM JSON_TABLE(
      p_denuncia_json, '$.productos[*]'
      COLUMNS (
        rn                            FOR ORDINALITY,
        tipo_producto_id              NUMBER        PATH '$.tipo_producto_id',
        nombre_producto_texto         VARCHAR2(200) PATH '$.nombre_producto_texto',
        registro_sanitario_ingresado  VARCHAR2(30)  PATH '$.registro_sanitario_ingresado',
        descripcion_producto          VARCHAR2(500) PATH '$.descripcion_producto',
        marca_ingresada               VARCHAR2(150) PATH '$.marca_ingresada',
        numero_lote                   VARCHAR2(50)  PATH '$.numero_lote',
        fabricante_ingresado          VARCHAR2(200) PATH '$.fabricante_ingresado',
        pais_origen                   VARCHAR2(100) PATH '$.pais_origen',
        presentacion                  VARCHAR2(100) PATH '$.presentacion',
        fecha_compra_txt              VARCHAR2(10)  PATH '$.fecha_compra',
        motivos_json                  VARCHAR2(4000) FORMAT JSON PATH '$.motivos'
      )
    ) jt
  )
  LOOP
    v_num_productos := v_num_productos + 1;

    IF fn_texto_valido(prod.nombre_producto_texto) = 'N' THEN
      RAISE_APPLICATION_ERROR(-20009, 'El nombre del producto #' || prod.rn || ' es obligatorio.');
    END IF;
    IF fn_texto_valido(prod.descripcion_producto) = 'N' THEN
      RAISE_APPLICATION_ERROR(-20010, 'La descripcion del producto #' || prod.rn || ' es obligatoria.');
    END IF;

    -- PUNTO 2: tipo_producto_id es obligatorio (el formulario lo entrega
    -- como catalogo/select). Se valida aqui ademas del NOT NULL de tabla
    -- para dar un mensaje legible en vez de un ORA-01400 generico.
    IF prod.tipo_producto_id IS NULL THEN
      RAISE_APPLICATION_ERROR(-20013, 'El tipo de producto del producto #' || prod.rn || ' es obligatorio.');
    END IF;

    INSERT INTO detalle_producto (
      denuncia_id, tipo_producto_id, nombre_producto_texto,
      registro_sanitario_ingresado, descripcion_producto, marca_ingresada
    ) VALUES (
      p_id_denuncia, prod.tipo_producto_id, prod.nombre_producto_texto,
      NULLIF(TRIM(prod.registro_sanitario_ingresado), ''),
      prod.descripcion_producto,
      NULLIF(TRIM(prod.marca_ingresada), '')
    ) RETURNING id_detalle_producto INTO v_id_detalle_producto;

    INSERT INTO detalle_producto_compra (
      id_detalle_producto, numero_lote, fabricante_ingresado,
      pais_origen, presentacion, fecha_compra
    ) VALUES (
      v_id_detalle_producto,
      NULLIF(TRIM(prod.numero_lote), ''),
      NULLIF(TRIM(prod.fabricante_ingresado), ''),
      NULLIF(TRIM(prod.pais_origen), ''),
      NULLIF(TRIM(prod.presentacion), ''),
      CASE WHEN prod.fecha_compra_txt IS NOT NULL
           THEN TO_DATE(prod.fecha_compra_txt, 'YYYY-MM-DD') END
    );

    v_num_motivos := 0;
    FOR mot IN (
      SELECT VALUE AS id_motivo
      FROM JSON_TABLE(prod.motivos_json, '$[*]' COLUMNS (VALUE NUMBER PATH '$'))
    )
    LOOP
      v_num_motivos := v_num_motivos + 1;
      INSERT INTO detalle_producto_motivo (id_detalle_producto, id_motivo)
      VALUES (v_id_detalle_producto, mot.id_motivo);
    END LOOP;

    IF v_num_motivos = 0 THEN
      RAISE_APPLICATION_ERROR(-20011, 'El producto #' || prod.rn || ' debe tener al menos un motivo de denuncia.');
    END IF;
  END LOOP;

  IF v_num_productos = 0 THEN
    RAISE_APPLICATION_ERROR(-20012, 'La denuncia debe incluir al menos un producto.');
  END IF;

  ----------------------------------------------------------------
  -- 9. bitacora (evento automatico, sin funcionario detras)
  ----------------------------------------------------------------
  INSERT INTO bitacora (denuncia_id, funcionario_id, area_origen_id, tipo_registro, contenido)
  VALUES (p_id_denuncia, NULL, v_area_id, 'accion_obligatoria',
          'Denuncia recibida y registrada automaticamente en el sistema.');

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END sp_registrar_denuncia;
/

